import { cn } from '@/lib/utils'
import type { Metadata } from 'next'
import { Inter, Noto_Sans_JP } from 'next/font/google'
import localFont from 'next/font/local'

import './globals.css'

const gambarino = localFont({
  src: './_fonts/Gambarino-Regular.woff2',
  display: 'swap',
  variable: '--font-gambarino',
})

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const notoSansJP = Noto_Sans_JP({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-noto-sans-jp',
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html
      lang="ja"
      className={cn(gambarino.variable, inter.variable, notoSansJP.variable)}
    >
      <body>{children}</body>
    </html>
  )
}
